-- Migration script: Add expanded fields to criminals table for detailed data per revised model
ALTER TABLE criminals
  ADD COLUMN IF NOT EXISTS criminal_id VARCHAR(50) UNIQUE,
  ADD COLUMN IF NOT EXISTS status VARCHAR(255),
  ADD COLUMN IF NOT EXISTS aliases JSONB,
  ADD COLUMN IF NOT EXISTS dob VARCHAR(20),
  ADD COLUMN IF NOT EXISTS estimated_age VARCHAR(50),
  ADD COLUMN IF NOT EXISTS sex VARCHAR(30),
  ADD COLUMN IF NOT EXISTS nationality VARCHAR(100),
  ADD COLUMN IF NOT EXISTS ethnicity VARCHAR(100),
  ADD COLUMN IF NOT EXISTS appearance JSONB,
  ADD COLUMN IF NOT EXISTS locations JSONB,
  ADD COLUMN IF NOT EXISTS summary JSONB,
  ADD COLUMN IF NOT EXISTS forensics JSONB,
  ADD COLUMN IF NOT EXISTS evidence JSONB,
  ADD COLUMN IF NOT EXISTS witness JSONB;
